version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuild phase
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_HASH
      - echo "Fetching parameters from AWS Systems Manager Parameter Store..."
      - CLOUDFRONT_ID=$(aws ssm get-parameter --name CLOUDFRONT_ID --query "Parameter.Value" --output text)
      - S3_BUCKET=$(aws ssm get-parameter --name S3_BUCKET --query "Parameter.Value" --output text)
      - echo "CLOUDFRONT_ID=${CLOUDFRONT_ID}"
      - echo "S3_BUCKET=${S3_BUCKET}"
      - echo pre build completed....
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3 ${S3_BUCKET}...
      - aws s3 sync ./build s3://${S3_BUCKET}/
      - echo Clearing CloudFront cache for index.html
      - aws configure set preview.cloudfront true
      - echo CLOUDFRONT_ID $CLOUDFRONT_ID
      - aws cloudfront create-invalidation --distribution-id=${CLOUDFRONT_ID} --paths=/index.html
      - echo Build Success....
cache:
  paths:
    - 'node_modules/**/*'